# Changes here will be overwritten by Copier
_commit: 2.6.0
_src_path: gh:DiamondLightSource/python-copier-template
author_email: raymond.fan@diamond.ac.uk
author_name: Raymond Fan
component_lifecycle: production
component_owner: ''
component_type: library
description: Bluesky code for Diamond's surface and magnetic materials beamline.
distribution_name: sm_bluesky
docker: false
docs_type: sphinx
git_platform: github.com
github_org: DiamondLightSource
package_name: sm_bluesky
pypi: false
repo_name: sm-bluesky
type_checker: pyright
