---
api:
  url: http://0.0.0.0:8000
env:
  metadata:
    instrument: iXX
  sources:
    - kind: deviceManager
      module: dodal.beamlines.i09
      mock: True
    - kind: planFunctions
      module: dodal.plans
    - kind: planFunctions
      module: dodal.plan_stubs.wrapped
stomp:
  enabled: True
  url: tcp://localhost:61613/
